### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Just1Number** [agateau/mup#3]
```
$ mup
Traceback (most recent call last):
  File "/usr/bin/mup", line 9, in <module>
    load_entry_point('mup==1.0.0', 'gui_scripts', 'mup')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/mup/main.py", line 10, in <module>
    from window import Window
ImportError: No module named 'window'

$ sudo python /usr/lib/python3.4/site-packages/mup/main.py 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mup/main.py", line 10, in <module>
    from window import Window
  File "/usr/lib/python3.4/site-packages/mup/window.py", line 12, in <module>
    from view import View
  File "/usr/lib/python3.4/site-packages/mup/view.py", line 5, in <module>
    import converters
  File "/usr/lib/python3.4/site-packages/mup/converters/__init__.py", line 6, in <module>
    from htmlconverter import HtmlConverter
ImportError: No module named 'htmlconverter'
```

I can't figure out whats going wrong here.

I'm using antergos and installed all dependencies listed in the readme

**Comment by agateau** [comment]
Looks like you are using a distribution which sets Python 3 as the default Python version. Can you try to do the following:
1. Install Python 2
2. rm -rf /usr/lib/python3.4/site-packages/mup
3. install the application with Python 2, there should be a binary named `python2` so you should be able to install mup with:
   
   python2 setup.py install

**Comment by Just1Number** [comment]
Thanks for the quick help! That resolved the issue
